- name: Provision nginx web server
  hosts: ubuntu2
  gather_facts: yes
  become: yes
  become_method: sudo
  vars:
    nginx_version: 1.18.0-0ubuntu1.4
    nginx_custom_directory: /home/ubuntu/nginx
    web_server_port: 80
  tasks:
    - name: Update and upgrade apt
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
    - name: "Install nginx to version {{ nginx_version }}"
      apt:
        name: "nginx={{ nginx_version }}"
        state: present
    - name: Copy the nginx configuration file to the host
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
    - name: Create link to the new config to enable it
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: Create Nginx directory
      ansible.builtin.file:
        path: "{{ nginx_custom_directory }}"
        state: directory

    - name: Copy index.html to the Nginx directory
      copy:
        src: files/index.html
        dest: "{{ nginx_custom_directory }}/index.html"
    - name: Restart the Nginx service
      service:
        name: nginx
        state: restart