---
# install java openjdk 1.8
- name: install java jdk 1.8
  apt: name=openjdk-8-jdk
- name: add group tomcat
  group: name=tomcat
- name: add user tomcat
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo
- name: create tomcate directory
  file:
    path: /usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat
- name: Download Tomcat package
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_download_location }}"
- name: extract tomcat archive
  unarchive:
    src: "{{ tomcat_download_location }}"        
    dest: /usr/share/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
- name: copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systems"
- name: start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat.service
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"  